'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0)
export default function Home(){
 const [tab,setTab]=useState('dashboard'),[products,setProducts]=useState([]),[materials,setMaterials]=useState([]),[sales,setSales]=useState([]),[customer,setCustomer]=useState(''),[cart,setCart]=useState([])
 const [pid,setPid]=useState(''),[qty,setQty]=useState(1),[msg,setMsg]=useState('')
 async function load(){let p=await supabase.from('products').select('*').eq('active',true).order('category').order('name');let m=await supabase.from('materials').select('*').eq('active',true).order('name');let s=await supabase.from('sales').select('*').order('created_at',{ascending:false}).limit(50);setProducts(p.data||[]);setMaterials(m.data||[]);setSales(s.data||[])}
 useEffect(()=>{load()},[])
 function add(){let p=products.find(x=>x.id===pid);if(!p)return;setCart([...cart,{...p,qty:+qty,total:+qty*p.selling_price}])}
 async function checkout(){if(!customer||!cart.length)return setMsg('Isi customer dan produk');let subtotal=cart.reduce((a,x)=>a+x.total,0);let no='INV-'+Date.now();let {data,error}=await supabase.from('sales').insert({invoice_no:no,customer_id:null,status:'PAID',subtotal,total:subtotal,paid:subtotal,change_amount:0,payment_method:'CASH'}).select().single();if(error)return setMsg(error.message);await supabase.from('sale_items').insert(cart.map(x=>({sale_id:data.id,product_id:x.id,product_name:x.name,unit:x.unit,qty:x.qty,unit_price:x.selling_price,total:x.total})));setMsg('Transaksi tersimpan: '+no);setCart([]);setCustomer('');await load()}
 const nav=['dashboard','produk','stok','kasir','laporan']
 return <><header><b>BannerPrint Pro</b><span>Database Online • Percetakan</span></header><nav>{nav.map(x=><button className={tab===x?'on':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><main>
 {tab==='dashboard'&&<><h2>Dashboard</h2><div className="cards"><div>Produk<strong>{products.length}</strong></div><div>Bahan<strong>{materials.length}</strong></div><div>Stok roll<strong>Database aktif</strong></div><div>Penjualan<strong>{money(sales.reduce((a,x)=>a+(x.total||0),0))}</strong></div></div></>}
 {tab==='produk'&&<><h2>Master Produk & Harga</h2><table><thead><tr><th>Produk</th><th>Kategori</th><th>Satuan</th><th>Harga</th></tr></thead><tbody>{products.map(x=><tr><td>{x.name}</td><td>{x.category}</td><td>{x.unit}</td><td>{money(x.selling_price)}</td></tr>)}</tbody></table></>}
 {tab==='stok'&&<><h2>Stok Bahan</h2><table><thead><tr><th>Bahan</th><th>Lebar</th><th>Modal/m</th><th>Minimum</th></tr></thead><tbody>{materials.map(x=><tr><td>{x.name}</td><td>{x.width_cm} cm</td><td>{money(x.cost_per_meter)}</td><td>{x.minimum_meter} m</td></tr>)}</tbody></table><p>Stok fisik roll dicatat di tabel material_rolls melalui modul Stok Masuk berikutnya.</p></>}
 {tab==='kasir'&&<><h2>Kasir</h2><input placeholder="Customer" value={customer} onChange={e=>setCustomer(e.target.value)}/><select value={pid} onChange={e=>setPid(e.target.value)}><option value="">Pilih produk</option>{products.map(x=><option value={x.id}>{x.name} — {money(x.selling_price)}</option>)}</select><input type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/><button onClick={add}>Tambah</button><h3>Keranjang</h3>{cart.map(x=><p>{x.name} × {x.qty} = {money(x.total)}</p>)}<h2>{money(cart.reduce((a,x)=>a+x.total,0))}</h2><button onClick={checkout}>Bayar & Simpan Invoice</button><p>{msg}</p></>}
 {tab==='laporan'&&<><h2>Penjualan</h2><table><thead><tr><th>Invoice</th><th>Total</th><th>Status</th><th>Tanggal</th></tr></thead><tbody>{sales.map(x=><tr><td>{x.invoice_no}</td><td>{money(x.total)}</td><td>{x.status}</td><td>{new Date(x.created_at).toLocaleString('id-ID')}</td></tr>)}</tbody></table></>}
 </main><style jsx>{`body{background:#f4f6fa;color:#172033}header{padding:16px 22px;background:#111827;color:#fff;display:flex;justify-content:space-between}nav{padding:10px;background:#fff;border-bottom:1px solid #ddd}nav button{margin:4px;padding:9px 12px;border:0;border-radius:7px}.on{background:#2563eb;color:#fff}main{max-width:1200px;margin:auto;padding:22px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.cards div,table{background:#fff;padding:15px;border:1px solid #ddd;border-radius:8px}strong{display:block;font-size:22px;margin-top:8px}input,select{padding:10px;margin:5px;border:1px solid #ccc;border-radius:6px}table{width:100%;border-collapse:collapse;padding:0}td,th{padding:10px;border-bottom:1px solid #eee;text-align:left}@media(max-width:700px){.cards{grid-template-columns:1fr 1fr}}`}</style></>
}